[build]
  command = """
    cp admin/js/config.template.js admin/js/config.js && \
    sed -i 's/FIREBASE_API_KEY/'\"$FIREBASE_API_KEY\"'/g; \
    s/FIREBASE_AUTH_DOMAIN/'\"$FIREBASE_AUTH_DOMAIN\"'/g; \
    s/FIREBASE_PROJECT_ID/'\"$FIREBASE_PROJECT_ID\"'/g; \
    s/FIREBASE_STORAGE_BUCKET/'\"$FIREBASE_STORAGE_BUCKET\"'/g; \
    s/FIREBASE_MESSAGING_SENDER_ID/'\"$FIREBASE_MESSAGING_SENDER_ID\"'/g; \
    s/FIREBASE_APP_ID/'\"$FIREBASE_APP_ID\"'/g; \
    s/IMGBB_API_KEY/'\"$IMGBB_API_KEY\"'/g' admin/js/config.js
  """
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/admin-login.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200