name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create config file
        run: |
          echo "import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js';
          import { getAuth } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
          import { getFirestore } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js';

          export const config = {
            imgbbApiKey: '${{ secrets.IMGBB_API_KEY }}'
          };

          export const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}'
          };

          const app = initializeApp(firebaseConfig);
          export const auth = getAuth(app);
          export const db = getFirestore(app);" > admin/js/config.js
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . 